### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by robertmarsal** [marcbuils/Flippage#1]
Hello,

First of all thank you for creating this plugin. It's really helpful :smiley: 

Would it be possible to get this published to npm?

The reason I am asking is because I would like to be able to download this package as a dependency of my application instead of directly commiting it into my code. I think this is a common use case for most JavaScript libraries currently.

Please see the following link with information on how to do this easily:
http://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick

Regards,
Rob

**Comment by marcbuils** [comment]
Hi Rob,

Good Idea, thanks.  
Now, You can use the following command : 

```
npm install jquery-plugin-flippage
```

Best Regards,
Marc

**Comment by robertmarsal** [comment]
Awesome! Thank you for this.
